[package]
name = "interrupts"
version = "0.1.0"
authors = ["mordak <bmickael@student.42.fr>"]
edition = "2018"
license = "GPL3"
description = "A smart toolkit about IDT"
documentation = "cargo doc --open"
homepage = "index.html"

[dependencies]
bit_field = "0.10.0"
i386 = { path = "../i386" }