[package]
name = "dummy"
version = "0.1.0"
authors = ["mordak <bmickael@student.42.fr>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
kernel_modules = { path = "../dependencies/kernel_modules" }
interrupts = { path = "../dependencies/interrupts" }
