[package]
name = "elf_loader"
version = "0.1.0"
authors = ["vcombey <vcombey@student.42.fr>"]
edition = "2018"

[dependencies]
bitflags = "1.0.4"
terminal = { path = "../terminal" }

[features]
test = []
std-print = []